sonar.projectKey=FleetOps-V2_fleetops-auth-service
sonar.projectName=FleetOps Auth Service
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/target/**,**/build/**,**/dist/**,**/coverage/**
sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=**/*
